export const initialAdminBusinesses = [
  {
    id: 'LOC-10294',
    name: 'The Oak Bistro & Lounge',
    category: 'Restaurant',
    location: 'GRA, Port Harcourt',
    address: '14 Forces Avenue, Old GRA, Port Harcourt',
    city: 'Port Harcourt',
    state: 'Rivers State',
    status: 'Active',
    owner: 'Mercy Geoffrey',
    ownerEmail: 'mercy@oakbistro.ng',
    phone: '+234 803 234 5678',
    created: 'Sep 28, 2026',
    rating: 4.8,
    reviewsCount: 184,
    priceRange: '$$ Moderate • $15 - $35 per person',
    verified: true,
    thumbnail: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Refined dining, craft cocktails, and ambient rooftop terrace.',
    description: 'The Oak Bistro & Lounge brings together continental culinary expertise and vibrant local hospitality. Known for signature wood-fired grills, vintage wines, and cozy indoor seating.',
    amenities: ['Free Wi-Fi', 'Outdoor Seating', 'Parking Space', 'Air Conditioning', 'Accepts Cards'],
    services: ['Dine-in', 'Takeaway', 'Private Events'],
    hours: 'Mon - Sun: 10:00 AM - 11:30 PM'
  },
  {
    id: 'LOC-10293',
    name: 'Kelechi Sport Nutrition Hub',
    category: 'Healthcare',
    location: 'D/Line, Port Harcourt',
    address: '42 Aba Road, D/Line, Port Harcourt',
    city: 'Port Harcourt',
    state: 'Rivers State',
    status: 'Pending Review',
    owner: 'Kelechi Daniel',
    ownerEmail: 'k.daniel@sportnutri.ng',
    phone: '+234 812 445 9901',
    created: 'Sep 27, 2026',
    rating: 4.6,
    reviewsCount: 32,
    priceRange: '$$ Moderate • $10 - $50 items',
    verified: false,
    thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Certified athletic supplements, meal prep planning, and wellness consultations.',
    description: 'Comprehensive sports nutrition center providing vetted dietary supplements, protein formulations, and certified fitness diet plans.',
    amenities: ['Parking Space', 'Air Conditioning', 'Card Payment'],
    services: ['Store Pickup', 'Delivery', 'Consultation'],
    hours: 'Mon - Sat: 8:00 AM - 8:00 PM'
  },
  {
    id: 'LOC-10292',
    name: 'Genesis Hot Delicacies & Diner',
    category: 'Financial Services',
    location: 'Peter Odili Rd, PH',
    address: 'Plot 12 Peter Odili Road, Trans Amadi, Port Harcourt',
    city: 'Port Harcourt',
    state: 'Rivers State',
    status: 'Active',
    owner: 'Blessing David',
    ownerEmail: 'blessing@genesishot.ng',
    phone: '+234 809 333 1122',
    created: 'Sep 25, 2026',
    rating: 4.9,
    reviewsCount: 420,
    priceRange: '$ Affordable • $5 - $20 per meal',
    verified: true,
    thumbnail: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Authentic local dishes, quick bites, and catering for corporate gatherings.',
    description: 'Serving hot and fresh Nigerian delicacies, pastries, and lunch specials with unmatched speed and consistency.',
    amenities: ['Free Wi-Fi', 'Air Conditioning', 'Takeout Counter', 'POS Available'],
    services: ['Dine-in', 'Drive-thru', 'Catering'],
    hours: 'Mon - Sun: 7:00 AM - 10:00 PM'
  },
  {
    id: 'LOC-10291',
    name: 'Grills King Spot',
    category: 'Retail / Discount',
    location: 'GRA Phase 2, Port Harcourt',
    address: '8 Tombia Street, GRA Phase 2, Port Harcourt',
    city: 'Port Harcourt',
    state: 'Rivers State',
    status: 'Suspended',
    owner: 'Seymour Davis',
    ownerEmail: 'seymour@grillsking.com',
    phone: '+234 802 777 8899',
    created: 'Sep 24, 2026',
    rating: 4.3,
    reviewsCount: 89,
    priceRange: '$$ Moderate • $10 - $30',
    verified: false,
    thumbnail: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Barbecue platters, smoked meats, and outdoor chill spot.',
    description: 'Specializes in charcoal grilled ribs, spiced wings, and signature suya platters. Currently under license verification review.',
    amenities: ['Outdoor Seating', 'Live Sports TV'],
    services: ['Dine-in', 'Takeaway'],
    hours: 'Daily: 4:00 PM - 12:00 AM'
  },
  {
    id: 'LOC-10290',
    name: 'Grand Oasis Cafe & Bakery',
    category: 'Fitness / Sports',
    location: 'D/Line, Port Harcourt',
    address: '28 Elechi Beach Road, D/Line, Port Harcourt',
    city: 'Port Harcourt',
    state: 'Rivers State',
    status: 'Active',
    owner: 'Alex Doe',
    ownerEmail: 'alex@grandoasis.ng',
    phone: '+234 816 555 4321',
    created: 'Sep 22, 2026',
    rating: 4.7,
    reviewsCount: 154,
    priceRange: '$$ Moderate • $8 - $22',
    verified: true,
    thumbnail: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Artisanal breads, organic matcha, and freshly roasted single-origin coffee.',
    description: 'Cozy community cafe featuring European-style sourdough breads, artisan pastries, and high-speed workspaces for creative professionals.',
    amenities: ['Free High-Speed Wi-Fi', 'Power Sockets', 'Air Conditioning', 'Pet Friendly Patio'],
    services: ['Dine-in', 'Takeaway', 'Pre-orders'],
    hours: 'Mon - Sat: 7:00 AM - 7:00 PM'
  },
  {
    id: 'LOC-10289',
    name: 'Grand View Hotel',
    category: 'Hotel',
    location: 'Golf Club, Port Harcourt',
    address: '5 Golf Course Road, Port Harcourt',
    city: 'Port Harcourt',
    state: 'Rivers State',
    status: 'Inactive',
    owner: 'Godfrey Brown',
    ownerEmail: 'godfrey@grandview.ng',
    phone: '+234 803 100 2200',
    created: 'Sep 20, 2026',
    rating: 4.5,
    reviewsCount: 95,
    priceRange: '$$$$ Luxury • $120 - $350 per night',
    verified: false,
    thumbnail: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Scenic views of the golf greens with executive suites and fine dining.',
    description: 'Upscale boutique hotel with panoramic golf course vistas, Olympic swimming pool, and corporate event halls.',
    amenities: ['Free Wi-Fi', 'Swimming Pool', 'Golf Access', 'Valet Parking', 'Gym'],
    services: ['Room Service', 'Airport Shuttle', 'Event Hosting'],
    hours: '24/7 Front Desk'
  },
  {
    id: 'BID-09381',
    name: 'Artisan Roasters & Bakery',
    category: 'Food & Beverage -> Cafe & Bakery',
    subCategory: 'Restaurant & Bar',
    location: 'Downtown Core, Austin, TX',
    address: '400 Congress Ave, Suite 120',
    city: 'Austin',
    state: 'Texas 78701',
    neighborhood: 'Downtown Arts & Financial District',
    coordinates: '30.2672° N, 97.7431° W',
    status: 'Pending Review',
    owner: 'Marina Garcia',
    ownerEmail: 'hello@artisanroasters.example.com',
    phone: '+1 (512) 555-0184',
    whatsapp: '+1 (512) 555-0184',
    website: 'artisanroasters.example.com',
    created: 'Oct 24, 2026 - 14:32 UTC',
    rating: 4.9,
    reviewsCount: 28,
    priceRange: '$$ Moderate • $10 - $25 per person',
    verified: false,
    claimCode: '#AR-Austin-9242',
    isClaimed: true,
    thumbnail: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1600&q=80',
    tagline: 'Handcrafted espresso, fresh sourdough, and community gathering space.',
    description: 'Founded in 2018, Artisan Roasters & Bakery blends small-batch single-origin coffees alongside naturally fermented artisanal breads and Viennoiserie pastries. We partner directly with sustainable coffee farms in Colombia, Ethiopia, and Guatemala. Our open-concept seating provides high-speed fiber internet for remote workers, alongside outdoor terrace hospitality for weekend gatherings and private events.',
    hours: 'Mon - Fri: 6:30 AM - 6:00 PM\nSat - Sun: 7:00 AM - 5:00 PM',
    services: ['Dine-in', 'Takeaway', 'Curbside pickup', 'Workspace board', 'Private events'],
    amenities: ['Free Wi-Fi', 'Wheelchair accessible', 'Outdoor patio', 'Pet friendly', 'Power sockets'],
    media: {
      logo: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=400&q=80',
      cover: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1600&q=80',
      gallery: [
        { title: 'Exterior seating', url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=600&q=80' },
        { title: 'Espresso bar', url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=600&q=80' },
        { title: 'Bakery case', url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80' },
        { title: 'Patio area', url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=600&q=80' }
      ]
    },
    compliance: {
      taxId: true,
      addressMatch: true,
      pricingVerified: true,
      phoneEmailVerified: true
    },
    auditHistory: [
      { title: 'Assigned to simon', timestamp: 'Oct 25, 10:00 UTC - Assigned via Queue #4', type: 'assignment' },
      { title: 'Automated checks passed', timestamp: 'Oct 24, 14:35 UTC - Score: 0.94/1.00', type: 'system' },
      { title: 'Registration submitted', timestamp: 'Oct 24, 14:32 UTC - Marina Garcia [Owner]', type: 'submission' }
    ]
  },
  {
    id: 'BID-07742',
    name: 'The Grand Epic Hotel',
    category: 'Hotel',
    location: 'GRA Phase 1, Port Harcourt',
    address: '11 Aba Road, Port Harcourt',
    city: 'Port Harcourt',
    state: 'Rivers State',
    status: 'Documents Needed',
    owner: 'Emmanuel Victor',
    ownerEmail: 'emmanuel@grandepic.ng',
    phone: '+234 803 999 1100',
    created: 'Oct 22, 2026 - 11:20 AM',
    rating: 4.4,
    reviewsCount: 78,
    priceRange: '$$$ Upscale • $80 - $200 per night',
    verified: false,
    thumbnail: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Grand suites, conference facilities, and fine dining lounge.',
    description: 'Premier hospitality destination awaiting physical tax registration documents and fire safety certification.',
    amenities: ['Free Wi-Fi', 'Swimming Pool', 'Gym', 'Conference Rooms'],
    services: ['24/7 Room Service', 'Buffet Breakfast'],
    hours: '24/7 Service'
  }
]

export const initialNeedsAttentionItems = [
  {
    id: 'na-1',
    type: 'Business Approval',
    targetId: 'BID-09381',
    name: 'Artisan Bakery & Cafe',
    status: 'Pending Verification',
    submittedDate: 'Oct 24, 2026 - 10:15 AM',
    priority: 'High'
  },
  {
    id: 'na-2',
    type: 'Advertisement',
    targetId: 'ADV-402',
    name: 'Metro Fitness & Suites - Special Banner',
    status: 'Under Review',
    submittedDate: 'Oct 24, 2026 - 09:30 AM',
    priority: 'Medium'
  },
  {
    id: 'na-3',
    type: 'Featured Listing',
    targetId: 'FEAT-881',
    name: 'Licard Continental Fast Food',
    status: 'Payment Confirmed',
    submittedDate: 'Oct 23, 2026 - 04:45 PM',
    priority: 'Low'
  },
  {
    id: 'na-4',
    type: 'Promotion',
    targetId: 'PRM-109',
    name: 'High Road Restaurant',
    status: 'Pending Verification',
    submittedDate: 'Oct 23, 2026 - 02:18 PM',
    priority: 'Medium'
  },
  {
    id: 'na-5',
    type: 'Business Approval',
    targetId: 'BID-07742',
    name: 'The Grand Epic Hotel',
    status: 'Documents Needed',
    submittedDate: 'Oct 22, 2026 - 11:20 AM',
    priority: 'High'
  }
]
